---
- hosts: all
  remote_user: opc
  gather_facts: false
  become: true
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
    
  tasks:
    - name: install epel release
      package:
        name: epel-release

    - name: install base packages
      package:
        name: 
          - ansible
          - git
