---
- hosts: all
  become: true
  roles:
    - base
  vars:
    deployer_cron_job: ansible-pull -U https://github.com/laenglea/linuxcentralmgt.git -i hosts podman.yml
  tasks:
    - include_role: 
        name: podman
          #      when: 
          #- docker is defined
          #- docker == true
