---
# tasks file for docker
- name: server | software | docker | add repokeys
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: server | software | docker | install deps
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    - dnf-plugins-core
 
- name: server | software | docker | add docker-repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
 
- name: server | software | docker | enable docker-repo
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: 'docker-ce-stable'
    option: enabled
    value: 1
 
- name: server | software | docker | install docker
  dnf:
    name: docker-ce
    state: present
 
- name: server | software | docker | enable autostart & start service
  systemd:
    name: docker
    enabled: true
    state: started
 
- name: server | software | docker | get docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
 
- name: server | software | docker | symlink docker-compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link
 

